replicaCount: 1

image:
  repository: ghcr.io/phuongdnguyen/tempura
  pullPolicy: IfNotPresent
  tag: "sha256:2ce7369ea1d0952d7b7332b338871400940ca8d58444cc0adcd9732ac61990bf"

# Provide an explicit Redis address. If empty, the chart will default to the bundled Bitnami Redis service.
redisAddr: ""

service:
  type: ClusterIP
  port: 8088
  adminPort: 8089

redis:
  auth:
    enabled: false
  architecture: standalone
